alias sshb='ssh -p 351 ssh.chatswood.org.uk'
alias sshch='ssh gcdadmin@charlie.gcdtech.com'
alias sshgr='ssh -l root www.goreport.net'
alias sshh='ssh -l root dev.gcdtech.com'
alias sshmnw='ssh cw1.default.chatswood.uk0.bigv.io'
alias sshtunnel='ssh -C2qtNfg -o ServerAliveInterval=600 -D 3351 -p 351 mkelly@ssh.chatswood.org.uk'
alias sshvm='ssh redhat61'
