alias cdbl='cd $HOME/Dropbox/Sites/chatswood.org.uk/blog'
alias cdd='cd $HOME/Downloads'
alias cddf='cd $HOME/.dotfiles'
alias cddr='cd $HOME/Dropbox'
alias gcom='git checkout master'
alias gr='grep'
alias grep='grep --color'
alias gt='gittower'
alias h='history'
alias hgr='history | grep'
alias iperfc='iperf -i 1 -c'
alias iperfs='iperf -s'
alias l='/bin/ls -G'
if is_mac; then
  alias ls='exa'
fi
alias psg='ps -ef | grep'
alias vi='vim'
