alias cds='cd $SRC_HEAD; echo "Current codeline is $CODELINE"'
alias cddb='if [ $DERBASE ]; then cd $DERBASE; else echo "No DERBASE defined"; fi'
alias lsdb='ls -l $DERBASE'
alias rmdb='rm -rf $DERBASE/*'
alias genv='env | g SRC_HEAD; env | g MOD_BASE; env | g DERBASE; env | g SYSTEM'
alias testkit='export GMK_TEST_KIT=1'
alias cdsys='if [ $SYSTEM ]; then cd $SYSTEM; else echo "No SYSTEM defined"; fi'
alias cdmb='if [ $MOD_BASE ]; then cd $MOD_BASE; else echo "No MOD_BASE defined";fi'
alias cdws='cd /nfs-bfs/workspace/mkelly'
alias sr='pwd; su - root -c "bash --rcfile /users/mkelly/.bash_root"'
alias tcslog='tail -f /opt/opwv/oam/2.0/tomcat/logs/catalina.out'
alias tmeplog='tail -f /var/opt/opwv/logs/MepApp.log'
alias vmeplog='vi /var/opt/opwv/logs/MepApp.log'
alias setupdev='source ~/bin/setup_dev_variables'

