DEV_DIR=/Users/mkelly/Dropbox/Development/Git
LOCAL_DEV_DIR=/Users/mkelly/Development
SK_DEV_DIR=$LOCAL_DEV_DIR/SK
DROPBOX_DIR=$HOME/Dropbox
alias cdam='cd $SK_DEV_DIR/Ambur/primary'
alias cdbo='cd $SK_DEV_DIR/backoffice'
alias cdbwa='cd "$DROPBOX_DIR/Documents/Writing/Build WatchKit Apps"'
alias cdds='cd $DROPBOX_DIR/Sites'
alias cdev='cd $DEV_DIR'
alias cdevlocal='cd $LOCAL_DEV_DIR'
alias cdevsk='cd $SK_DEV_DIR'
alias cdir='cd $SK_DEV_DIR/ipad-register/primary; rvm use @register'
alias cdiralt='cd $SK_DEV_DIR/ipad-register/alt; rvm use @register'
alias cdsdk='cd $SK_DEV_DIR/SKBackofficeSDK; rvm use @sdk'
alias cdstg='cd "$DROPBOX_DIR/Documents/Writing/Swift Translation Guide"'
alias cdtr='cd $DEV_DIR/Trailer'
alias cdxcp='cd $DEV_DIR/XCPretty'
alias pusdk='be pod update SKBackofficeSDK'
alias sshci-hosted-pro-1='ssh_tunnel administrator@208.52.187.179 5921'
alias sshci-hosted-pro-2='ssh_tunnel administrator@208.52.187.102 5922'
alias sshci-hosted-pro-3='ssh_tunnel administrator@208.52.187.103 5923'
