#!/usr/bin/env zsh


install_cask anvil
install_cask appcode
install_cask base
install_cask coderunner
install_cask hex-fiend
install_cask hopper-disassembler
install_cask hype
install_cask ios-console
install_cask iphone-configuration-utility
install_cask kaleidoscope
install_cask reveal
install_cask sequel-pro
install_cask simpholders
install_cask tower
install_cask trailer
install_cask p4merge
install_cask xscope
