#!/usr/bin/env bash

if ! brew_cask_package_is_installed; then
  echo "Please install 'brew install cask' first"
  exit 1
fi

install_cask airfoil
install_cask fluid
install_cask ibank
install_cask kiwi
install_cask marked
install_cask netspot
install_cask nvalt
install_cask omnigraffle
install_cask omnioutliner
install_cask rdio
install_cask spotify
install_cask transmit

# missing casks
# metaz
# transporter desktop
