#!/usr/bin/env zsh

if ! brew_cask_package_is_installed; then
  echo "Please install 'brew install cask' first"
  exit 1
fi

install_cask airfoil
install_cask airserver
install_cask fluid
install_cask ibank
install_cask marked
install_cask netspot
install_cask nvalt
install_cask omnifocus
install_cask omnioutliner
install_cask slack
install_cask sonos
install_cask spotify
install_cask transmit
install_cask transporter-desktop

# missing casks
# metaz
