#!/usr/bin/env bash

if ! brew_cask_package_is_installed; then
  echo "Please install 'brew install cask' first"
  exit 1
fi

install_cask bartender
install_cask crashplan
install_cask dropbox
install_cask evernote
install_cask google-chrome
install_cask hipchat
install_cask iterm2
install_cask launchbar
install_cask little-snitch
install_cask skype
install_cask textexpander
install_cask superduper
